<?php

namespace FacturaScripts\Plugins\Oftalmol\src;

class TestTypes {

    const TEST_TYPE_AUTOREFRACTOMETER = 1;
    const TEST_TYPE_SHIASCOPY = 2;
    const TEST_TYPE_FRONTOFOCOMETER = 3;
    const TEST_TYPE_SUBJETIVEREFRACTION = 4;
    const TEST_TYPE_BIOMICROSCOPY = 5;
    const TEST_TYPE_EYEFUNDUS = 6;
    const TEST_TYPE_GONIOSCOPY = 7;
    const TEST_TYPE_EXOPHTHALMOMETRY = 8;
    const TEST_TYPE_EYELIDFUNCTION = 9;
    const TEST_TYPE_STEREOPSIS = 10;
    const TEST_TYPE_COVERTEST = 11;
    const TEST_TYPE_WORTHLIGHTS = 12;
    const TEST_TYPE_BIELSCHOSWSKY = 13;
    const TEST_TYPE_OCULARMOTILITY = 14;
    const TEST_TYPE_CONVERGENCEPOINT = 15;
}

