<?php

namespace FacturaScripts\Plugins\Oftalmol\src;

class TestTypes {

    //TEST TYPES OF REFRACTION
    const TEST_TYPE_VISUALACUITY = 0;
    const TEST_TYPE_AUTOREFRACTOMETER = 1;
    const TEST_TYPE_SHIASCOPY = 2;
    const TEST_TYPE_FRONTOFOCOMETER = 3;
    const TEST_TYPE_SUBJETIVEREFRACTION = 4;
    
    //TEST TYPES OF SLIT LAMP
    const TEST_TYPE_BIOMICROSCOPY = 5;
    const TEST_TYPE_EYEFUNDUS = 6;
    const TEST_TYPE_GONIOSCOPY = 7;
    
    //TEST TYPES OF INTRAOCULAR PRESSURE
    const TEST_TYPE_TONOMETRY = 8;
    const TEST_TYPE_TONOMETRYBRALEY = 9;
    const TEST_TYPE_PACHYMETRY = 10;
}
